### ISSUE TITLE
Display stand hover texture

### ISSUE THREAD

**Issue by CARDS1031** [runescapejon/TransformersMod#2]
The display stand changes textures (in inventory/hotbar) when the cursor passes over another block or the display stand itself.

[Display Stand](https://gyazo.com/5332b6c61e333830cfa6f16e6846ca20)

**Comment by runescapejon** [comment]
still not fixed ?

**Comment by CARDS1031** [comment]
Verison 0.6.1.55 has fixed the issue.

**Comment by runescapejon** [comment]
_Fixed_
